/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MiniCategory: typeof import('./src/components/mini-category.vue')['default']
    MiniCategoryPane: typeof import('./src/components/mini-category-pane.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
  }
}
